name: CDK integration

on: [push, pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and start mint
        run: |
          docker run -d -p 3338:3338 \
          --name cdk-mint \
          -e CDK_MINTD_DATABASE=sqlite \
          -e CDK_MINTD_LN_BACKEND=fakewallet \
          -e CDK_MINTD_INPUT_FEE_PPK=100 \
          -e CDK_MINTD_LISTEN_HOST=0.0.0.0 \
          -e CDK_MINTD_LISTEN_PORT=3338 \
          -e CDK_MINTD_MNEMONIC='abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about' \
          cashubtc/mintd:latest-amd64
      - name: Check running containers
        run: docker ps

      - name: Sleep 5 seconds and curl on localhost:3338/v1/info
        run: |
          sleep 30
          curl localhost:3338/v1/info

      - name: Checkout cashu-ts repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - run: npm ci
      - run: npm run compile
      - run: npm run test-integration
